# Generated by Django 4.1.7 on 2023-04-03 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(8)])),
                ('problem_id', models.IntegerField(default=-1)),
                ('username', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
