# Generated by Django 4.1.7 on 2023-04-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_insight_rename_name_hint_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HintCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField(default=-1)),
                ('hint_id', models.IntegerField(default=-1)),
                ('cluster_id', models.IntegerField(default=-1)),
                ('first', models.BooleanField(default=False)),
            ],
        ),
    ]
