# Generated by Django 4.1.7 on 2023-04-25 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_hintcluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hintcluster',
            name='hint_id',
        ),
        migrations.AddField(
            model_name='hintcluster',
            name='hint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.hint'),
        ),
    ]
