# Generated by Django 4.1.7 on 2023-04-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_insightcluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightcluster',
            name='insight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.insight'),
        ),
    ]
