# Generated by Django 4.2.1 on 2023-05-14 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_insightcluster_insight'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallInsightCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField(default=-1)),
                ('cluster_id_overall', models.IntegerField(default=-1)),
                ('cluster_id_in_problem', models.IntegerField(default=-1)),
                ('insight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.insight')),
            ],
        ),
    ]
