# Generated by Django 4.2.1 on 2023-08-02 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0010_alter_problem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('IP', 'In progress'), ('NHS', 'Needed help to solve'), ('SO', 'Solved')], default='NS', max_length=20)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
        ),
    ]
