# Generated by Django 4.2.1 on 2023-08-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalproblem',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
