# Generated by Django 4.2.1 on 2023-08-02 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalproblem_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalproblem',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
