# Generated by Django 4.2.1 on 2023-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalproblem_time_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('type_filter', models.CharField(choices=[('entire', 'entire'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='entire', max_length=6)),
            ],
        ),
    ]
