# Generated by Django 4.2.1 on 2023-08-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journalconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalconfig',
            name='desired_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='desired_week',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='journalconfig',
            name='desired_year',
            field=models.IntegerField(default=2023),
        ),
    ]
