# Generated by Django 4.2.1 on 2023-08-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_journalconfig_desired_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalconfig',
            name='desired_page',
            field=models.IntegerField(default=0),
        ),
    ]
