# Generated by Django 4.2.1 on 2023-08-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_journalconfig_desired_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalconfig',
            name='desired_page',
            field=models.IntegerField(default=1),
        ),
    ]
