# Generated by Django 4.0.2 on 2022-02-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='problem_submissions',
            field=models.JSONField(),
            preserve_default=False,
        ),
    ]
