# Generated by Django 4.0.2 on 2022-02-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_problem_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contest_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='problem_submissions',
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_rating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
