# Generated by Django 4.1.7 on 2023-04-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_contest_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
    ]
