# Generated by Django 4.2.4 on 2023-10-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NP', 'Not Processed'), ('CU', 'Currently Processing'), ('FI', 'Finished Processed')], default='NS', max_length=20)),
            ],
        ),
    ]
