# Generated by Django 4.2.4 on 2023-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importstatus',
            name='status',
            field=models.CharField(choices=[('NP', 'Not Processed'), ('CU', 'Currently Processing'), ('FI', 'Finished Processed')], default='NP', max_length=20),
        ),
    ]
