# Generated by Django 4.2.4 on 2023-10-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0002_alter_importstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importstatus',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
